db-uri            = "postgres://authenticator:devsecret@localhost:5432/portsmith"
db-schemas        = "api"
db-anon-role      = "web_anon"
jwt-secret        = "portsmith-lab-book-dev-secret-do-not-use-in-production"
db-channel-enabled = true
db-channel        = "pgrst"
server-port       = 3000