services:
  pg18:
    build: .
    environment:
      POSTGRES_USER: chris
      POSTGRES_PASSWORD: ch22-scratch
      POSTGRES_DB: portsmith22
    ports:
      - "5434:5432"
    volumes:
      - pg18-data:/var/lib/postgresql/18/main

volumes:
  pg18-data:
